const StudentData = [
  {
    "SNo": 1,
    "PassedOut": 2023,
    "id": "AP22110010001",
    "name": "ADITYA DHIR",
    "personelEmail": "adityadhir97@gmail.com",
    "Program": "B.Tech.",
    "Branch": "Computer Science and Engineering",
    "School": "SEAS",
    "email": "aditya_dhir@srmap.edu.in",
    "gender": "Male",
    "dob": "26-Nov-97",
    "mobile": "889726 / 9871879199",
    "CGPA": 8.55,
    "Salary": 1,
    "job": "Razor Network Pte Ltd,16 Robinson Road #14-4,Singapore",
    "MastersCollege": "",
    "MastersProgram": "",
    "LinkedIn": "linkedin.com/in/adityadhir",
    "PresentStatus": "Software engineer MetaKeep",
    "PresentLocation": "Delhi",
    "PathChosen": "Job",
    "AlumniPortalRegistered": "No",
    "imageURL": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqTj7AO5WS4cU_lqk1Ky8IwOA_qugUry7WYw&s",
    "Section": "A"
  },
  {
    "SNo": 2,
    "PassedOut": 2020,
    "id": "AP22110010002",
    "name": "RAMPATI VENKAT TARUN",
    "personelEmail": "tarunrampati@gmail.com",
    "Program": "B.Tech.",
    "Branch": "Electronics and Communication Engineering",
    "School": "SEAS",
    "email": "venkat_tarun@srmap.edu.in",
    "gender": "Male",
    "dob": "25-Jun-99",
    "mobile": "996321921 / 83961385",
    "CGPA": 9.9,
    "Salary": 4,
    "job": "Ivy Software Development Services Private Limited,Sth Floor, \"8\" Block, Divyasree Omega, Kondapur, Hyderabad,",
    "MastersCollege": "",
    "MastersProgram": "",
    "LinkedIn": "linkedin.com/in/tarun-rampati-56686194",
    "PresentStatus": "Trainee Software Engineer at IVY Software Development Services Private Limited",
    "PresentLocation": "Hyderabad",
    "PathChosen": "Job",
    "AlumniPortalRegistered": "Yes",
    "imageURL": "",
    "Section": "A"
  },
  {
    "SNo": 3,
    "PassedOut": 2024,
    "id": "AP22110010003",
    "name": "SAJAN KUMAR",
    "personelEmail": "ksajan12@gmail.com",
    "Program": "B.Tech.",
    "Branch": "Electronics and Communication Engineering",
    "School": "SEAS",
    "email": "sajan_kumar@srmap.edu.in",
    "gender": "",
    "dob": "04-Apr-98",
    "mobile": "9654799429 / 944988918",
    "CGPA": 9.13,
    "Salary": 65,
    "job": "FACE PREP-Focus 4 – D Career Education Pvt Ltd,Lakshmi Nagar, Thottipalayam Pirivu, Avinashi Road, Coimbatore",
    "MastersCollege": "",
    "MastersProgram": "",
    "LinkedIn": "linkedin.com/in/ksajan",
    "PresentStatus": "CoinDCX AS Software Developer",
    "PresentLocation": "Bengaluru",
    "PathChosen": "Job",
    "AlumniPortalRegistered": "Yes",
    "imageURL": "",
    "Section": "A"
  },
  {
    "SNo": 4,
    "PassedOut": 2022,
    "id": "AP22110010004",
    "name": "SAURABH SUNIL GHANEKAR",
    "personelEmail": "ghanekarsaurabh8@gmail.com",
    "Program": "B.Tech.",
    "Branch": "Media Studies",
    "School": "SEAS",
    "email": "sunil_ghanekar@srmap.edu.in",
    "gender": "",
    "dob": "23-Dec-98",
    "mobile": "942948855/\t982595832",
    "CGPA": 9.6,
    "Salary": "",
    "job": "",
    "MastersCollege": "",
    "MastersProgram": "",
    "LinkedIn": "",
    "PresentStatus": "",
    "PresentLocation": "",
    "PathChosen": "",
    "AlumniPortalRegistered": "No",
    "imageURL": "",
    "Section": "A"
  },
  {
    "SNo": 5,
    "PassedOut": 2022,
    "id": "AP22110010005",
    "name": "RAMYA AMBATI",
    "personelEmail": "ramyaambati12@gmail.com",
    "Program": "B.Tech.",
    "Branch": "Management",
    "School": "SEAS",
    "email": "ramya_ambati@srmap.edu.in",
    "gender": "",
    "dob": "14-Sep-99",
    "mobile": "7995227591/\t95938",
    "CGPA": 7.51,
    "Salary": 462,
    "job": "InfoCepts Technologies Private Limited,Parsodi, Gayatri Nagar, Pratap Nagar, Nagpur",
    "MastersCollege": "",
    "MastersProgram": "",
    "LinkedIn": "https://www.linkedin.com/in/ramya-ambati/",
    "PresentStatus": "Masters in Data Analytics Engineering In Northeastern Univeristy",
    "PresentLocation": "Massachusetts United state",
    "PathChosen": "Masters",
    "AlumniPortalRegistered": "No",
    "imageURL": "",
    "Section": "A"
  },
  {
    "SNo": 6,
    "PassedOut": 2021,
    "id": "AP22110010006",
    "name": "PESALA SAI TANMAYI",
    "personelEmail": "tkagencies@gmail.com",
    "Program": "B.Tech.",
    "Branch": "Electrical and Electronics Engineering",
    "School": "SEAS",
    "email": "sai_tanmayi@srmap.edu.in",
    "gender": "",
    "dob": "06-Dec-99",
    "mobile": "9246416611 / 912116611",
    "CGPA": 8.98,
    "Salary": 46,
    "job": "Cognizant Technology Solutions,DLF IT Park Rd, Manapakkam, Chennai",
    "MastersCollege": "University of Leicester, M.Sc International Business Management",
    "MastersProgram": "",
    "LinkedIn": "https://www.linkedin.com/in/tanmayipesala/",
    "PresentStatus": "University of Leicester MBA",
    "PresentLocation": "United Kingdom",
    "PathChosen": "Masters",
    "AlumniPortalRegistered": "No",
    "imageURL": "",
    "Section": "A"
  },
  {
    "SNo": 7,
    "PassedOut": 2021,
    "id": "AP22110010007",
    "name": "NEHA NIMMAGADDA",
    "personelEmail": "nimmagaddaneha@gmail.com",
    "Program": "B.Tech.",
    "Branch": "Computer Science and Engineering",
    "School": "SEAS",
    "email": "neha_nimmagadda@srmap.edu.in",
    "gender": "",
    "dob": "02-Jan-02",
    "mobile": 63165516,
    "CGPA": 7.56,
    "Salary": 8,
    "job": "Honeywell, Bangalore",
    "MastersCollege": "",
    "MastersProgram": "",
    "LinkedIn": "linkedin.com/in/neha-nimmagadda-244ab3193",
    "PresentStatus": "Masters / University of North Texas",
    "PresentLocation": "Texas, United States",
    "PathChosen": "Masters",
    "AlumniPortalRegistered": "No",
    "imageURL": "",
    "Section": "A"
  },
  {
    "SNo": 8,
    "PassedOut": 2021,
    "id": "AP22110010008",
    "name": "KAMAL GUDE",
    "personelEmail": "gudekamal52@gmail.com",
    "Program": "B.Tech.",
    "Branch": "Computer Science and Engineering",
    "School": "SEAS",
    "email": "kamal_gude@srmap.edu.in",
    "gender": "",
    "dob": "27-Nov-99",
    "mobile": 9848627899,
    "CGPA": 6.37,
    "Salary": "",
    "job": "",
    "MastersCollege": "New York Institute of Technology",
    "MastersProgram": "Masters in Computer and Information Sciences",
    "LinkedIn": "",
    "PresentStatus": "New York Institute of Technology in CSE",
    "PresentLocation": "New york",
    "PathChosen": "Masters",
    "AlumniPortalRegistered": "No",
    "imageURL": "",
    "Section": "A"
  },
  {
    "SNo": 9,
    "PassedOut": 2019,
    "id": "AP22110010009",
    "name": "KOMMINENI JAGADEESH CHOWDARY",
    "personelEmail": "jagadeeshchowdary.k1999@gmail.com",
    "Program": "B.Tech.",
    "Branch": "Computer Science and Engineering",
    "School": "SEAS",
    "email": "kommineni_jagadeesh@srmap.edu.in",
    "gender": "",
    "dob": "17-Nov-99",
    "mobile": "94945275/795215988",
    "CGPA": 8.51,
    "Salary": 462,
    "job": "InfoCepts Technologies Private Limited,Parsodi, Gayatri Nagar, Pratap Nagar, Nagpur",
    "MastersCollege": "",
    "MastersProgram": "",
    "LinkedIn": "",
    "PresentStatus": "Masters/Concordia University, Montreal",
    "PresentLocation": "Canada",
    "PathChosen": "Masters",
    "AlumniPortalRegistered": "Yes",
    "imageURL": "",
    "Section": "A"
  },
  {
    "SNo": 10,
    "PassedOut": 2019,
    "id": "AP22110010010",
    "name": "KOYA VENKAT SAI VARA PRASAD",
    "personelEmail": "koyavenkat7@gmail.com",
    "Program": "B.Tech.",
    "Branch": "Computer Science and Engineering",
    "School": "SEAS",
    "email": "venkat_saivaraprasad@srmap.edu.in",
    "gender": "",
    "dob": "09-Jan-02",
    "mobile": 93294445,
    "CGPA": 7.82,
    "Salary": "",
    "job": "",
    "MastersCollege": "",
    "MastersProgram": "",
    "LinkedIn": "",
    "PresentStatus": "Master",
    "PresentLocation": "",
    "PathChosen": "Masters",
    "AlumniPortalRegistered": "Yes",
    "imageURL": "",
    "Section": "A"
  }
];

export default StudentData;